name: Upload to S3

on: [pull_request]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: AKIAVG7GN3FPHCKBFHFD
          aws_secret_access_key: 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
          aws_bucket: test-data-kari-bucket
          source_dir: 'tests'
